export const ArticleType = [
	'JavaScript',
	'Node.js',
	'Vue',
	'React',
	'Html5',
	'Html/CSS',
	'Angular',
	'WebApp',
	'Jquery',
	'Bootstrap',
	'前端工具',
	'CSS3',
	'Sass/Less',
	'JAVA',
	'Python',
	'Go',
	'PHP',
	'C',
	'C++',
	'C#',
	'MySQL',
	'SQL Server',
	'Oracle',
	'MongoDB',
	'Android',
	'iOS',
	'Unity 3D',
	'Cocos2d-x',
	'大数据',
	'云计算',
	'深度学习',
	'机器学习',
	'测试',
	'Linux',
	'Photoshop',
	'Maya',
	'Premiere',
	'ZBrush',
	'数据结构',
	'Ruby'
]

export const ArticleCategory = [ '资讯', '区块链', '人工智能', '云计算/大数据', '前端开发', '后端开发', '移动互联', '工具资源', '职场生活', '幽默段子', '其他' ]
export const ArticleCategoryAll = [ '全部' ,...ArticleCategory]
export const defaultAvatar = require(`./assets/imgs/defaultAvatar.jpg`)
export const reportReason = ['广告或垃圾信息', '辱骂', '涉政或违法', '抄袭', '不合适内容']